language: node_js
node_js:
- '10'
before_install:
- npm install
- npm run fix-lint
- npm test
script:
- npm run build
deploy:
  provider: npm
  email: bervianto.leo@gmail.com
  api_key:
    secure: eWaZH3bDgqTYetpDOMOV3p/pFRWaZ8tVj73ijDlFLtfNJ/loo6jaGIPa8gYaWKUwFQgW1ZyGdnOd6SmW0b8dE+TDJ1XYYGosF9AKWCFxJec91NOznuZWlEIInWn7HgPafhFTueQs4bvgGzhi+KgEhAlNzewt/tcrRj/48etpHO8zbkmDka19zpdW8TtqqZ6VRFnf+BZ7oTYJq9gnO8lQ+p8Ao1TcZ3uMKmwzvHXWtl9/mGR9YyCSSgiXtVLGdOv45SYVp4YHWBxkprck/ILtyMfrkoGdWl7v94q4hrlRqEwr6NMXV2/tRKW20cLZB2koxQJYcKRYB8Fwjgh+hAz6KdUExQuuzyhP11YiiBnfpOK/HIYXyrl92LaDUAVL+4G35x2H+h+f5BsU4lS0r2/vOEoz9Y281mkmuUCEGgzJPDjtCb9PbSIwdnOBF5WEbv5yztByd433n+95ilZoK8cGR2/4/Z+n4f8fFWBxM615EodDcXxAIoxHRUwpEKZRgSFkOdcHseoqj9R4whKjxHwSfTKGTJ+n7ZHZOVqxM1iNuSVrYv6E7W9MG4Vkvzs9CTNW1FVvMWE1ysL4+eFY3YYnIEPvHauivq6lFgzfgSNxCwGRUeeY539kAPeHSFWVo8OYrNtngTh+oM3UxbR2mYwM7rSgiEmbLGiX2+rZse/KfZM=
  skip_cleanup: true
  on:
    tags: true
